Adjust GHA to build runtimes from fellows and sdk repos
paritytech/srtool pull request #75
Opened 2023-10-23 14:07 UTC by EgorPopelyaev

This PR adjusts both GHA's to build runtimes from the `fellowship` and `sdk` repos:
1. Added possibility to set the repo from where to build runtimes
2. Refactored caching: now the as a cache key used the ref from the target repo (`polkadot-sdk` or `polkadot-fellows/runtimes`)

2023-10-23 14:25 UTC, chevdor requested changes
small fixes

2023-10-23 14:25 UTC, chevdor commented on .github/workflows/manual-fellow-runtimes.yml
> +          TOML_CLI_VERSION=0.2.4
We have ENV at the top, that's a good place to keep such information together.
I would suggest moving that one up with  `SUBWASM_VERSION`.

2023-10-23 14:26 UTC, EgorPopelyaev commented on .github/workflows/manual-fellow-runtimes.yml
> +        uses: chevdor/srtool-actions@wk-230920-add-debug
Totally agree, then we need to wait till those changes are going to be released

2023-10-30 16:00 UTC, chevdor approved these changes

2023-10-31 07:07 UTC, merged